package com.anand.pdf.create;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.UUID;

public class LargePdfGenerator {

    public static File createLargeTextPdf(
            int pages,
            String outputFile)
            throws Exception {

        File file = new File(outputFile);

        file.getParentFile().mkdirs();

        PDDocument document = new PDDocument();

        try {

            for (int pageNo = 1; pageNo <= pages; pageNo++) {

                PDPage page = new PDPage(PDRectangle.A4);
                document.addPage(page);

                PDPageContentStream cs =
                        new PDPageContentStream(
                                document,
                                page);

                cs.beginText();

                cs.setFont(
                        PDType1Font.HELVETICA,
                        8);

                cs.newLineAtOffset(20, 800);

                cs.showText(
                        "Generated By Legacy System");

                cs.newLineAtOffset(0, -20);

                for (int line = 1; line <= 100; line++) {

                    StringBuilder sb =
                            new StringBuilder();

                    sb.append("Page=")
                            .append(pageNo)
                            .append(" Line=")
                            .append(line)
                            .append(" ");

                    for (int i = 0; i < 20; i++) {

                        sb.append(UUID.randomUUID())
                                .append(" ");
                    }

                    cs.showText(sb.toString());

                    cs.newLineAtOffset(0, -7);
                }

                cs.endText();
                cs.close();

                if (pageNo % 100 == 0) {

                    System.out.println(
                            "Generated page "
                                    + pageNo);
                }
            }

            document.save(file);

        } finally {

            document.close();
        }

        return file;
    }

    public static File createImagePdf(
            int pages,
            String outputPath)
            throws Exception {

        File output = new File(outputPath);

        File parent = output.getParentFile();
        System.out.println("Creating " + output.getAbsolutePath());
//        if (parent != null && !parent.exists()) {
//            parent.mkdirs();
//        }

        PDDocument doc =
                new PDDocument();
        BufferedImage image = createLargeImage();

        PDImageXObject pdImage =
                LosslessFactory.createFromImage(
                        doc,
                        image);
        for(int i=1;i<=pages;i++) {

            PDPage page =
                    new PDPage(
                            PDRectangle.A4);

            doc.addPage(page);

            PDPageContentStream cs =
                    new PDPageContentStream(
                            doc,
                            page);
            cs.drawImage(
                    pdImage,
                    20,
                    100,
                    500,
                    500);
            cs.beginText();

            cs.setFont(
                    PDType1Font.HELVETICA,
                    12);

            cs.newLineAtOffset(
                    50,
                    700);

            cs.showText(
                    "Page " + i);

            cs.endText();

            //Add Original Footer
            cs.beginText();

            cs.setFont(
                    PDType1Font.HELVETICA,
                    8);

            cs.newLineAtOffset(
                    50,
                    20);

            cs.showText(
                    "Generated By Legacy System");

            cs.endText();

            cs.close();
        }

        doc.save(output);

        doc.close();

        return output;
    }

    private static BufferedImage createLargeImage() {

        BufferedImage image =
                new BufferedImage(
                        3000,
                        3000,
                        BufferedImage.TYPE_INT_RGB);

        Graphics2D g = image.createGraphics();

        g.setColor(Color.BLUE);
        g.fillRect(0,0,3000,3000);

        g.setColor(Color.WHITE);

        for(int i=0;i<500;i++) {

            g.drawString(
                    UUID.randomUUID().toString(),
                    50,
                    50 + i * 5);
        }

        g.dispose();

        return image;
    }
}
